import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";

test("additive Drive migration preserves legacy storage and enforces provider, role, credential and lease boundaries", async () => {
  const db = new PGlite();
  const owner = "10000000-0000-0000-0000-000000000001", editor = "10000000-0000-0000-0000-000000000002";
  const viewer = "10000000-0000-0000-0000-000000000003", outsider = "10000000-0000-0000-0000-000000000004";
  const id = "20000000-0000-0000-0000-000000000001", legacy = "20000000-0000-0000-0000-000000000002", hash = "a".repeat(64);
  const as = async (user: string) => { await db.exec("reset role"); await db.query("select set_config('request.jwt.claim.sub',$1,false)", [user]); await db.exec("set role authenticated"); };
  const state = (id: string) => JSON.stringify({ schema: "opentakeoff.cloud.v1", annotations: { schema: "opentakeoff.takeoff_canvas.v1", project_id: id, project_name: "Test", conditions: [], shapes: [] }, plans: [{ sha256: hash }], snapshots: [] });
  try {
    await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
      create schema auth; create schema storage;
      create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
      create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
      grant usage on schema auth,public,storage to authenticated,anon,service_role;
      create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
      create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,unique(bucket_id,name));
      alter table storage.objects enable row level security;
      grant select,insert,update,delete on storage.objects to authenticated;`);
    await db.exec(await readFile(new URL("../../supabase/migrations/202609270001_optional_cloud.sql", import.meta.url), "utf8"));
    for (const [user, name] of [[owner, "owner"], [editor, "editor"], [viewer, "viewer"], [outsider, "outsider"]]) await db.query("insert into auth.users values($1,$2,now())", [user, `${name}@example.com`]);
    await as(owner);
    await db.query("select otk_save_project($1,0,$2::jsonb)", [legacy, state(legacy)]);
    await db.query("select otk_register_file($1,$2,'legacy.pdf','application/pdf',100)", [legacy, hash]);
    await db.query("insert into storage.objects(bucket_id,name) values('otk-project-files',$1)", [`${legacy}/${hash}`]);
    await db.query("select otk_finish_file($1,$2)", [legacy, hash]);
    await db.exec("reset role");
    await db.exec(await readFile(new URL("../../supabase/migrations/202609270002_drive_files.sql", import.meta.url), "utf8"));
    await as(owner);
    const original: any = (await db.query("select * from otk_project_files where project_id=$1", [legacy])).rows[0];
    assert.equal(original.storage_provider, "supabase"); assert.equal(original.uploaded, true);
    assert.equal((await db.query("select * from storage.objects")).rows.length, 1);
    await assert.rejects(db.query("select otk_set_file_provider($1,'google_drive')", [legacy]), /OTK_PROVIDER_LOCKED/);
    await db.query("select otk_save_project($1,0,$2::jsonb)", [id, state(id)]);
    await assert.rejects(db.query("select otk_set_file_provider($1,'google_drive')", [id]), /OTK_DRIVE_CONNECT/);
    for (const table of ["otk_drive_connections", "otk_drive_oauth", "otk_drive_uploads"]) await assert.rejects(db.query(`select * from ${table}`), /permission denied/);
    await db.exec("reset role; set role service_role");
    await db.query("insert into otk_drive_connections(user_id,google_sub,email,token_cipher,status) values($1,'google','private@example.com','encrypted','connected')", [owner]);
    await as(owner); await db.query("select otk_set_file_provider($1,'google_drive')", [id]);
    await db.query("select otk_register_file($1,$2,'plan.pdf','application/pdf',100)", [id, hash]);
    const row: any = (await db.query("select * from otk_project_files where project_id=$1", [id])).rows[0];
    assert.equal(row.storage_provider, "google_drive"); assert.equal(row.file_kind, "originals"); assert.equal(row.provider_owner_id, owner); assert.equal(row.uploaded, false);
    await assert.rejects(db.query("select otk_set_file_provider($1,'supabase')", [id]), /OTK_PROVIDER_LOCKED/);
    await assert.rejects(db.query("select otk_finish_file($1,$2)", [id, hash]), /OTK_ACCESS/);
    await assert.rejects(db.query("insert into storage.objects(bucket_id,name) values('otk-project-files',$1)", [`${id}/${hash}`]), /row-level security/);
    await assert.rejects(db.query("select otk_drive_lease($1,$2,$3)", [id, hash, owner]), /permission denied/);
    await db.query("select otk_share_project($1,'editor@example.com','editor')", [id]);
    await db.query("select otk_share_project($1,'viewer@example.com','viewer')", [id]);
    await as(editor); await db.query("select otk_register_file($1,$2,'board.png','image/png',10)", [id, "b".repeat(64)]);
    await assert.rejects(db.query("select otk_set_file_provider($1,'supabase')", [id]), /OTK_ACCESS/);
    await as(viewer); assert.equal((await db.query("select * from otk_project_files")).rows.length, 2);
    await assert.rejects(db.query("update otk_project_files set uploaded=true"), /permission denied/);
    await assert.rejects(db.query("select otk_register_file($1,$2,'other.pdf','application/pdf',100)", [id, hash]), /OTK_ACCESS/);
    await as(outsider); assert.equal((await db.query("select * from otk_project_files")).rows.length, 0);
    await db.exec("reset role; set role service_role");
    assert.equal((await db.query<any>("select otk_drive_lease($1,$2,$3) as ok", [id, hash, owner])).rows[0].ok, true);
    assert.equal((await db.query<any>("select otk_drive_lease($1,$2,$3) as ok", [id, hash, editor])).rows[0].ok, false);
    await db.query("update otk_project_files set provider_file_id='stable-id',uploaded=true where project_id=$1 and sha256=$2", [id, hash]);
    await db.query("insert into otk_drive_oauth values('state',$1,'cipher','https://app',now()+interval '1 minute')", [owner]);
    assert.equal((await db.query("select * from otk_drive_claim_oauth('state')")).rows.length, 1);
    assert.equal((await db.query("select * from otk_drive_claim_oauth('state')")).rows.length, 0);
    await as(owner); await db.query("select otk_remove_member($1,$2)", [id, viewer]);
    await as(viewer); assert.equal((await db.query("select * from otk_project_files")).rows.length, 0);
    await as(owner); await db.query("select otk_delete_project($1,1)", [id]);
    await assert.rejects(db.query("select otk_purge_project($1)", [id]), /OTK_FILES_REMAIN/);
    await db.exec("reset role; set role service_role");
    await db.query("update otk_project_files set provider_file_id=null where project_id=$1", [id]);
    await as(owner); await assert.rejects(db.query("select otk_purge_project($1)", [id]), /OTK_FILES_REMAIN/);
    await db.exec("reset role; set role service_role");
    await db.query("update otk_drive_uploads set lease_until=null where project_id=$1", [id]);
    await as(owner); await db.query("select otk_purge_project($1)", [id]);
    assert.equal((await db.query("select * from otk_projects")).rows.length, 1);
  } finally { await db.close(); }
});
